"""
Document Generator - PowerPoint, Memos, and Drawings
Location: server/managers/document_generator.py
"""
import logging
import os
from typing import Dict, Any, List, Optional
from datetime import datetime
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt
from docx import Document
from docx.shared import Inches as DocxInches, Pt as DocxPt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from PIL import Image, ImageDraw, ImageFont
import svgwrite

logger = logging.getLogger("document_generator")

# Data paths
DATA_DIR = Path(os.path.expanduser("~/Library/Application Support/ExecutiveAssistant/data"))
DOCS_DIR = DATA_DIR / "documents"
TEMPLATES_DIR = DATA_DIR / "templates"


class DocumentGenerator:
    """Generates PowerPoint presentations, memos, and drawings"""
    
    def __init__(self):
        DOCS_DIR.mkdir(parents=True, exist_ok=True)
        TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
        
    def _sanitize_filename(self, name: str) -> str:
        """Create safe filename"""
        safe = "".join(c if c.isalnum() or c in [' ', '_', '-'] else '_' for c in name)
        return safe.strip().replace(' ', '_')[:100]
    
    def create_powerpoint(self, title: str, slides: List[Dict], 
                         template: Optional[str] = None, **kwargs) -> Dict[str, Any]:
        """
        Create a PowerPoint presentation
        
        Args:
            title: Presentation title
            slides: List of slide dicts with 'title' and 'content' or 'bullets'
            template: Optional template name
            
        Returns:
            Created presentation info
        """
        try:
            prs = Presentation()
            
            # Set slide size (16:9)
            prs.slide_width = Inches(10)
            prs.slide_height = Inches(7.5)
            
            # Title slide
            title_slide_layout = prs.slide_layouts[0]
            slide = prs.slides.add_slide(title_slide_layout)
            title_shape = slide.shapes.title
            subtitle = slide.placeholders[1]
            
            title_shape.text = title
            subtitle.text = f"Generated by Executive Assistant\n{datetime.now().strftime('%B %d, %Y')}"
            
            # Content slides
            for slide_data in slides:
                # Choose layout based on content type
                if "bullets" in slide_data:
                    # Bullet point layout
                    bullet_slide_layout = prs.slide_layouts[1]
                    slide = prs.slides.add_slide(bullet_slide_layout)
                    
                    title_shape = slide.shapes.title
                    body_shape = slide.placeholders[1]
                    
                    title_shape.text = slide_data.get("title", "")
                    
                    text_frame = body_shape.text_frame
                    text_frame.clear()
                    
                    bullets = slide_data["bullets"]
                    if isinstance(bullets, str):
                        bullets = [b.strip() for b in bullets.split('\n') if b.strip()]
                    
                    for bullet in bullets:
                        p = text_frame.add_paragraph()
                        p.text = bullet
                        p.level = 0
                        
                elif "content" in slide_data:
                    # Title and content layout
                    content_slide_layout = prs.slide_layouts[5]  # Blank layout
                    slide = prs.slides.add_slide(content_slide_layout)
                    
                    # Add title
                    left = Inches(0.5)
                    top = Inches(0.5)
                    width = Inches(9)
                    height = Inches(1)
                    
                    title_box = slide.shapes.add_textbox(left, top, width, height)
                    title_frame = title_box.text_frame
                    title_frame.text = slide_data.get("title", "")
                    title_frame.paragraphs[0].font.size = Pt(32)
                    title_frame.paragraphs[0].font.bold = True
                    
                    # Add content
                    left = Inches(0.5)
                    top = Inches(1.75)
                    width = Inches(9)
                    height = Inches(5)
                    
                    content_box = slide.shapes.add_textbox(left, top, width, height)
                    content_frame = content_box.text_frame
                    content_frame.text = slide_data["content"]
                    content_frame.word_wrap = True
                    content_frame.paragraphs[0].font.size = Pt(18)
            
            # Save presentation
            filename = self._sanitize_filename(title) + ".pptx"
            filepath = DOCS_DIR / filename
            prs.save(str(filepath))
            
            logger.info(f"Created PowerPoint: {title}")
            
            return {
                "status": "success",
                "title": title,
                "filename": filename,
                "path": str(filepath),
                "slide_count": len(prs.slides),
                "timestamp": datetime.now().isoformat()
            }
            
        except Exception as e:
            logger.error(f"Error creating PowerPoint: {e}")
            return {"status": "error", "error": str(e)}
    
    def create_memo(self, to: str, from_: str, subject: str, content: str, **kwargs) -> Dict[str, Any]:
        """
        Create a memo document
        
        Args:
            to: Recipient
            from_: Sender
            subject: Memo subject
            content: Memo body
            
        Returns:
            Created memo info
        """
        try:
            doc = Document()
            
            # Set margins
            sections = doc.sections
            for section in sections:
                section.top_margin = DocxInches(1)
                section.bottom_margin = DocxInches(1)
                section.left_margin = DocxInches(1)
                section.right_margin = DocxInches(1)
            
            # Title
            title = doc.add_heading('MEMORANDUM', 0)
            title.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
            doc.add_paragraph()
            
            # Header fields
            header_style = doc.styles['Normal']
            
            to_para = doc.add_paragraph()
            to_para.add_run('TO: ').bold = True
            to_para.add_run(to)
            
            from_para = doc.add_paragraph()
            from_para.add_run('FROM: ').bold = True
            from_para.add_run(from_)
            
            date_para = doc.add_paragraph()
            date_para.add_run('DATE: ').bold = True
            date_para.add_run(datetime.now().strftime('%B %d, %Y'))
            
            subject_para = doc.add_paragraph()
            subject_para.add_run('SUBJECT: ').bold = True
            subject_para.add_run(subject)
            
            # Horizontal line
            doc.add_paragraph('_' * 80)
            
            doc.add_paragraph()
            
            # Body content
            # Split content into paragraphs
            paragraphs = content.split('\n\n')
            for para_text in paragraphs:
                if para_text.strip():
                    doc.add_paragraph(para_text.strip())
            
            # Save document
            filename = self._sanitize_filename(f"memo_{subject}") + ".docx"
            filepath = DOCS_DIR / filename
            doc.save(str(filepath))
            
            logger.info(f"Created memo: {subject}")
            
            return {
                "status": "success",
                "subject": subject,
                "filename": filename,
                "path": str(filepath),
                "timestamp": datetime.now().isoformat()
            }
            
        except Exception as e:
            logger.error(f"Error creating memo: {e}")
            return {"status": "error", "error": str(e)}
    
    def create_drawing(self, description: str, format: str = "png", **kwargs) -> Dict[str, Any]:
        """
        Create a simple drawing/diagram
        
        Args:
            description: What to draw (simple shapes/diagrams)
            format: Output format ('png' or 'svg')
            
        Returns:
            Created drawing info
        """
        try:
            # Parse description for basic shapes
            # This is a simplified implementation - real version would use AI
            
            width = 800
            height = 600
            
            if format.lower() == "svg":
                return self._create_svg_drawing(description, width, height)
            else:
                return self._create_png_drawing(description, width, height)
            
        except Exception as e:
            logger.error(f"Error creating drawing: {e}")
            return {"status": "error", "error": str(e)}
    
    def _create_png_drawing(self, description: str, width: int, height: int) -> Dict[str, Any]:
        """Create PNG drawing"""
        try:
            # Create image
            img = Image.new('RGB', (width, height), color='white')
            draw = ImageDraw.Draw(img)
            
            # Try to load a font, fall back to default
            try:
                font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 24)
                title_font = ImageFont.truetype("/System/Library/Fonts/Helvetica.ttc", 32)
            except:
                font = ImageFont.load_default()
                title_font = ImageFont.load_default()
            
            # Draw title
            draw.text((20, 20), "Drawing", fill='black', font=title_font)
            
            # Parse description for simple shapes
            desc_lower = description.lower()
            
            if "circle" in desc_lower:
                # Draw a circle
                center_x, center_y = width // 2, height // 2
                radius = 100
                draw.ellipse(
                    [center_x - radius, center_y - radius, center_x + radius, center_y + radius],
                    outline='blue', width=3
                )
                draw.text((center_x - 30, center_y - 10), "Circle", fill='blue', font=font)
            
            if "square" in desc_lower or "rectangle" in desc_lower:
                # Draw a rectangle
                left, top = 100, 200
                right, bottom = 300, 400
                draw.rectangle([left, top, right, bottom], outline='red', width=3)
                draw.text((left + 50, top + 90), "Rectangle", fill='red', font=font)
            
            if "arrow" in desc_lower:
                # Draw an arrow
                start_x, start_y = 400, 300
                end_x, end_y = 600, 300
                draw.line([start_x, start_y, end_x, end_y], fill='green', width=3)
                # Arrow head
                draw.polygon([
                    (end_x, end_y),
                    (end_x - 15, end_y - 10),
                    (end_x - 15, end_y + 10)
                ], fill='green')
            
            # Add description text
            draw.text((20, height - 100), f"Description: {description[:50]}", fill='gray', font=font)
            
            # Save image
            filename = self._sanitize_filename(f"drawing_{description[:30]}") + ".png"
            filepath = DOCS_DIR / filename
            img.save(str(filepath))
            
            logger.info(f"Created PNG drawing: {description[:50]}")
            
            return {
                "status": "success",
                "description": description,
                "filename": filename,
                "path": str(filepath),
                "format": "png",
                "timestamp": datetime.now().isoformat()
            }
            
        except Exception as e:
            logger.error(f"Error creating PNG drawing: {e}")
            return {"status": "error", "error": str(e)}
    
    def _create_svg_drawing(self, description: str, width: int, height: int) -> Dict[str, Any]:
        """Create SVG drawing"""
        try:
            filename = self._sanitize_filename(f"drawing_{description[:30]}") + ".svg"
            filepath = DOCS_DIR / filename
            
            dwg = svgwrite.Drawing(str(filepath), size=(width, height))
            
            # Add title
            dwg.add(dwg.text("Drawing", insert=(20, 40), font_size=32, fill='black'))
            
            # Parse description for simple shapes
            desc_lower = description.lower()
            
            if "circle" in desc_lower:
                dwg.add(dwg.circle(center=(width // 2, height // 2), r=100, 
                                  stroke='blue', stroke_width=3, fill='none'))
                dwg.add(dwg.text("Circle", insert=(width // 2 - 30, height // 2), 
                                font_size=24, fill='blue'))
            
            if "square" in desc_lower or "rectangle" in desc_lower:
                dwg.add(dwg.rect(insert=(100, 200), size=(200, 200),
                                stroke='red', stroke_width=3, fill='none'))
                dwg.add(dwg.text("Rectangle", insert=(150, 300), 
                                font_size=24, fill='red'))
            
            if "arrow" in desc_lower:
                dwg.add(dwg.line(start=(400, 300), end=(600, 300),
                                stroke='green', stroke_width=3))
                dwg.add(dwg.polygon(points=[(600, 300), (585, 290), (585, 310)],
                                   fill='green'))
            
            # Add description
            dwg.add(dwg.text(f"Description: {description[:50]}", 
                           insert=(20, height - 50), font_size=18, fill='gray'))
            
            dwg.save()
            
            logger.info(f"Created SVG drawing: {description[:50]}")
            
            return {
                "status": "success",
                "description": description,
                "filename": filename,
                "path": str(filepath),
                "format": "svg",
                "timestamp": datetime.now().isoformat()
            }
            
        except Exception as e:
            logger.error(f"Error creating SVG drawing: {e}")
            return {"status": "error", "error": str(e)}